### ISSUE TITLE
Error on mission launch.

### ISSUE THREAD

**Issue by rhyswilliams999** [john681611/resistance3#131]
Getting Spammed in the rpt with this error message:

22:03:00   Error Type Array, expected String
22:03:00 File mpmissions\__cur_mp.cup_chernarus_A3\Server\persistance\content\setContent.sqf..., line 39
22:03:00 Error in expression <0),1,((_x select 4) select 1)];
};
_box additemcargoGlobal [(_x select 5),1];
} >

**Comment by rhyswilliams999** [comment]
changing line 39 to include a if statement seems to fix the issue.
was: _box additemcargoGlobal [(_x select 5),1];

fix: if(count (_x select 5) > 0) then {_box additemcargoGlobal [(_x select 5),1];};

**Comment by john681611** [comment]
While this fix is fine it also indicates something isn't working as expected.
